# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Dev

pool:
  vmImage: ubuntu-latest

steps:
- task: SpecFlowPlus@0
  displayName: 'SpecFlow + LivingDoc  generation'
  inputs:
    generatorSource: 'FeatureFolder'
    projectFilePath: 'CommunityContentSubmissionPage.Specs/Features'
    projectName: 'Community Content Submission Page'
    projectLanguage: 'en'
    workItemPrefix: 'testPrefix'
  enabled: true
  continueOnError: true
  condition: always()
  timeoutInMinutes: 10
